# Generated by Django 3.1.1 on 2020-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataread',
            name='dr_city',
            field=models.CharField(default='Bangalore', max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='dataread',
            name='dr_data',
            field=models.CharField(default='', max_length=250, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='dataread',
            name='dr_fname',
            field=models.CharField(max_length=15, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='dataread',
            name='dr_id',
            field=models.IntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dataread',
            name='dr_lname',
            field=models.CharField(max_length=15, verbose_name='Last Name'),
        ),
    ]
