# Generated by Django 3.1.1 on 2020-09-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonread', '0002_auto_20200907_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataread',
            name='dr_data',
            field=models.TextField(default='', max_length=250, verbose_name='Data'),
        ),
    ]
